//! Test-only generator and drift check for the checked-in `docs/api.md`
//! (regen: `npm run api:gen`). Scrapes the `("METHOD", [segs])` arms in
//! `src/route/` and `bin/headless.rs`; notes come from the handler's `///`.

use std::collections::{HashMap, HashSet};
use std::path::Path;

const METHODS: [&str; 5] = ["GET", "POST", "PUT", "PATCH", "DELETE"];

const HEADER: &str = "\
<!-- Generated by `npm run api:gen` from the route arms in
src-tauri/crates/server/src/route/ and bin/headless.rs. DO NOT EDIT: `npm run
api:check` (and `cargo test`) fails when this file drifts from the source. -->

# HTTP API

JSON in, JSON out. The app reaches these routes through the `api` Tauri
command (`share_api` for `/api/share/*`); the headless bin serves them over
HTTP, and the dev shim serves all but `/api/share/*`. Errors carry
`{status, detail}` over IPC and `{detail}` with the HTTP status over HTTP.

**Body** and **Response** name the wire struct (see `src/types/generated.ts`)
when the handler names one directly; blank means not statically named. **Notes**
is the handler's doc comment.
";

/// One documented handler: its doc prose (route spans stripped), the query
/// string its doc names, and the body/response types its fn body names.
#[derive(Default, Clone)]
struct Handler {
    query: String,
    notes: String,
    body: String,
    resp: String,
}

/// Source text minus the trailing `#[cfg(test)] mod`, whose fixtures look like arms.
fn non_test(src: &str) -> &str {
    src.find("\n#[cfg(test)]\nmod ").map_or(src, |i| &src[..i])
}

/// `` `GET /api/x/{id}?q=` `` → `("GET", "/api/x/{id}", "?q=")`.
fn parse_span(span: &str) -> Option<(&str, &str, &str)> {
    let (method, rest) = span.split_once(' ')?;
    if !METHODS.contains(&method) || !rest.starts_with('/') {
        return None;
    }
    let (path, query) = rest.find('?').map_or((rest, ""), |i| rest.split_at(i));
    Some((method, path, query))
}

/// Match key: `{param}` names differ between arms and docs, so blank them.
fn key(method: &str, path: &str) -> String {
    let segs: Vec<&str> = path
        .split('/')
        .map(|s| if s.starts_with('{') { "{}" } else { s })
        .collect();
    format!("{method} {}", segs.join("/"))
}

/// Text of the fn starting at `lines[start]`, through its closing brace.
fn fn_body(lines: &[&str], start: usize) -> String {
    let indent = &lines[start][..lines[start].len() - lines[start].trim_start().len()];
    let close = format!("{indent}}}");
    let end = lines[start..]
        .iter()
        .position(|l| *l == close)
        .map_or(lines.len(), |i| start + i + 1);
    lines[start..end].join("\n")
}

/// The UpperCamel identifier at the start of `s`, if any.
fn type_ident(s: &str) -> Option<&str> {
    let end = s
        .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
        .unwrap_or(s.len());
    let id = &s[..end];
    id.starts_with(|c: char| c.is_ascii_uppercase())
        .then_some(id)
}

/// Body type: `let b: T = ctx.parse_body()` or `parse_body::<T>()`.
fn body_type(body: &str) -> String {
    if let Some(i) = body.find("parse_body::<") {
        return type_ident(&body[i + 13..]).unwrap_or_default().to_string();
    }
    for line in body.lines().filter(|l| l.contains(".parse_body()")) {
        if let Some((_, ty)) = line.split_once(": ") {
            if let Some(id) = type_ident(ty) {
                return id.to_string();
            }
        }
    }
    String::new()
}

/// Response type: the first struct handed to `to_value(&T` / `json(StatusCode::OK, &T`.
fn resp_type(body: &str) -> String {
    ["to_value(&", "json(StatusCode::OK, &"]
        .iter()
        .filter_map(|pat| {
            body.match_indices(pat)
                .find_map(|(i, _)| type_ident(&body[i + pat.len()..]).map(|t| (i, t)))
        })
        .min()
        .map(|(_, t)| t.to_string())
        .unwrap_or_default()
}

/// Leading backtick route spans of a doc (`` `GET /api/a` and `GET /api/b` — prose ``)
/// and the prose after them.
fn doc_routes(text: &str) -> (Vec<(&str, &str, &str)>, &str) {
    let mut rest = text;
    let mut routes = Vec::new();
    while let Some(span) = rest.strip_prefix('`') {
        let Some(end) = span.find('`') else { break };
        let Some(route) = parse_span(&span[..end]) else {
            break;
        };
        routes.push(route);
        rest = span[end + 1..].trim_start_matches([' ', ',', '/']);
        rest = rest
            .strip_prefix("and ")
            .or(rest.strip_prefix("or "))
            .unwrap_or(rest);
    }
    (
        routes,
        rest.trim_start_matches([' ', '.', ',', ':', ';', '—', '-'])
            .trim(),
    )
}

/// Every `///` block whose leading spans name routes, keyed by route. Above a
/// `fn`, it's the handler: notes, plus the types its body names. Above a
/// `struct`, the struct is that route's request body (prose starts "request
/// body"/"body") or response; it fills only what the handler left blank.
fn handlers(src: &str) -> HashMap<String, Handler> {
    let lines: Vec<&str> = src.lines().collect();
    let mut out: HashMap<String, Handler> = HashMap::new();
    let mut from_structs: Vec<(String, Handler)> = Vec::new();
    let mut doc: Vec<&str> = Vec::new();
    for (i, line) in lines.iter().enumerate() {
        let t = line.trim_start();
        if let Some(d) = t.strip_prefix("///") {
            doc.extend(Some(d.trim()).filter(|d| !d.is_empty()));
            continue;
        }
        if t.starts_with("#[") {
            continue;
        }
        let text = doc.join(" ");
        doc.clear();
        let (routes, notes) = doc_routes(&text);
        if routes.is_empty() || t.starts_with("//") {
            continue;
        }
        let mut h = Handler {
            notes: notes.to_string(),
            ..Handler::default()
        };
        if t.contains("fn ") {
            let body = fn_body(&lines, i);
            h.body = body_type(&body);
            h.resp = resp_type(&body);
        } else if let Some((_, after)) = t.split_once("struct ") {
            let name = type_ident(after).unwrap_or_default().to_string();
            let lower = notes.to_lowercase();
            if lower.starts_with("entry") || lower.starts_with("row") {
                continue; // an element type, not the route's envelope
            }
            let label = ["request body", "body", "envelope"]
                .iter()
                .find(|p| lower.starts_with(**p));
            if let Some(p) = label {
                h.notes = notes[p.len()..]
                    .trim_start_matches([' ', '.', ',', ':', ';'])
                    .to_string();
            }
            match label {
                Some(&"envelope") | None => h.resp = name,
                Some(_) => h.body = name,
            }
        } else {
            continue;
        }
        for (method, path, query) in routes {
            let h = Handler {
                query: query.to_string(),
                ..h.clone()
            };
            if t.contains("fn ") {
                out.insert(key(method, path), h);
            } else {
                from_structs.push((key(method, path), h));
            }
        }
    }
    for (k, s) in from_structs {
        let h = out.entry(k).or_default();
        for (field, val) in [
            (&mut h.query, s.query),
            (&mut h.notes, s.notes),
            (&mut h.body, s.body),
            (&mut h.resp, s.resp),
        ] {
            if field.is_empty() {
                *field = val;
            }
        }
    }
    out
}

/// `("METHOD", [ "api", "x", id ])` arms, in source order, as `(method, path)`.
/// `"a" | "b"` segments expand to one route each; bindings become `{name}`.
fn segment_arms(src: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for (i, _) in src.match_indices("(\"") {
        let rest = &src[i + 2..];
        let Some(method) = METHODS
            .iter()
            .find(|m| rest.starts_with(&format!("{m}\", [")))
        else {
            continue;
        };
        let pat = &rest[method.len() + 4..];
        let Some(end) = pat.find(']') else { continue };
        let mut paths = vec![String::new()];
        for seg in pat[..end]
            .split(',')
            .map(str::trim)
            .filter(|s| !s.is_empty())
        {
            let alts: Vec<String> = if seg.starts_with('"') {
                seg.split('|')
                    .map(|a| a.trim().trim_matches('"').to_string())
                    .collect()
            } else if let Some((name, _)) = seg.split_once(" @ ..") {
                vec![format!("{{{name}..}}")]
            } else if seg == "_" {
                vec!["{_}".to_string()]
            } else {
                vec![format!("{{{seg}}}")]
            };
            paths = paths
                .iter()
                .flat_map(|p| alts.iter().map(move |a| format!("{p}/{a}")))
                .collect();
        }
        out.extend(paths.into_iter().map(|p| (method.to_string(), p)));
    }
    out
}

/// Headless arms: `("METHOD", CONST)`, `("METHOD", p) if p.starts_with("…")`, and
/// `Method::GET && req.uri().path() == CONST|"…"`, resolving `const X: &str`.
fn headless_arms(src: &str) -> Vec<(String, String)> {
    let consts: HashMap<&str, &str> = src
        .lines()
        .filter_map(|l| l.strip_prefix("const ")?.split_once(": &str = \""))
        .map(|(name, v)| (name, v.trim_end_matches("\";")))
        .collect();
    let resolve = |s: &str| -> Option<String> {
        let s = s.trim();
        s.strip_prefix('"')
            .map(|q| q.trim_end_matches('"').to_string())
            .or_else(|| consts.get(s).map(|v| v.to_string()))
    };
    let mut out = Vec::new();
    for line in src.lines().map(str::trim) {
        for m in METHODS {
            if let Some(rest) = line.strip_prefix(&format!("(\"{m}\", ")) {
                let (arg, tail) = rest.split_once(')').unwrap_or((rest, ""));
                if let Some(path) = resolve(arg) {
                    out.push((m.to_string(), path));
                } else if let Some(pre) = tail.split_once(".starts_with(\"").map(|(_, p)| p) {
                    let pre = &pre[..pre.find('"').unwrap_or(pre.len())];
                    out.push((m.to_string(), format!("{pre}{{id}}")));
                }
            }
            let probe = format!("Method::{m} && req.uri().path() == ");
            if let Some(i) = line.find(&probe) {
                let arg = line[i + probe.len()..].trim_end_matches(" {");
                if let Some(path) = resolve(arg) {
                    out.push((m.to_string(), path));
                }
            }
        }
    }
    out
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

/// One `##` section: a table of `arms`, joined to `docs` by method + path.
fn section(
    title: &str,
    link: &str,
    arms: &[(String, String)],
    docs: &HashMap<String, Handler>,
    seen: &mut HashSet<String>,
) -> String {
    let mut rows = String::new();
    for (method, path) in arms {
        let k = key(method, path);
        if !seen.insert(k.clone()) {
            continue;
        }
        let h = docs.get(&k).cloned().unwrap_or_default();
        let ty = |t: &str| {
            if t.is_empty() {
                String::new()
            } else {
                format!("`{t}`")
            }
        };
        rows.push_str(&format!(
            "| {method} | `{}{}` | {} | {} | {} |\n",
            cell(path),
            cell(&h.query),
            ty(&h.body),
            ty(&h.resp),
            cell(&h.notes)
        ));
    }
    if rows.is_empty() {
        return String::new();
    }
    format!(
        "\n## {title}\n\nSource: [`{link}`](../src-tauri/crates/server/src/{link})\n\n\
         | Method | Path | Body | Response | Notes |\n|---|---|---|---|---|\n{rows}"
    )
}

pub(crate) fn render() -> String {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files: Vec<_> = std::fs::read_dir(src_dir.join("route"))
        .expect("read src/route")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "rs"))
        .collect();
    files.sort();
    let mut seen = HashSet::new();
    let mut out = HEADER.to_string();
    for path in files {
        let src = std::fs::read_to_string(&path).expect("read route file");
        let src = non_test(&src);
        let stem = path.file_stem().unwrap().to_string_lossy();
        let title = if stem == "mod" {
            "top-level".into()
        } else {
            stem.replace('_', "-")
        };
        let link = format!("route/{stem}.rs");
        out.push_str(&section(
            &title,
            &link,
            &segment_arms(src),
            &handlers(src),
            &mut seen,
        ));
    }
    let headless =
        std::fs::read_to_string(src_dir.join("bin/headless.rs")).expect("read headless.rs");
    let headless = non_test(&headless);
    out.push_str(&section(
        "headless only",
        "bin/headless.rs",
        &headless_arms(headless),
        &handlers(headless),
        &mut seen,
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::render;

    /// Repo-root-relative: this crate is `<repo>/src-tauri/crates/server`.
    const API_DOC: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../../docs/api.md");

    #[test]
    fn api_doc_is_current() {
        let want = render();
        if std::env::var_os("UPDATE_API_DOCS").is_some() {
            std::fs::write(API_DOC, &want).expect("write docs/api.md");
            return;
        }
        let have = std::fs::read_to_string(API_DOC).unwrap_or_default();
        let first_diff = have
            .lines()
            .zip(want.lines())
            .position(|(a, b)| a != b)
            .map(|i| i + 1);
        assert!(
            have == want,
            "docs/api.md is stale (first differing line: {first_diff:?}) — run `npm run api:gen`"
        );
    }
}
