CREATE TABLE IF NOT EXISTS AUTHOR(
    AUTHOR_FK INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_FULL_NAME TEXT,
    AUTHOR_FIRST TEXT,
    AUTHOR_LAST TEXT,
    AUTHOR_ORCID TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT (date('now')),
    UPDATED_AT TEXT NOT NULL DEFAULT (date('now'))
);
