CREATE TABLE AUTHOR(
    AUTHOR_SK INTEGER NOT NULL,
    AUTHOR_FULL_NAME VARCHAR(500),
    AUTHOR_FIRST VARCHAR(255),
    AUTHOR_LAST VARCHAR(255),
    AUTHOR_ORCID VARCHAR(255),
    PRIMARY KEY AUTHOR_SK       
);