CREATE TABLE IF NOT EXISTS DB_VERSION (
    VERSION_FK  INTEGER   PRIMARY KEY AUTOINCREMENT,
    VERSION     TEXT      NOT NULL UNIQUE,
    APPLIED_AT  TIMESTAMP NOT NULL DEFAULT (datetime('now'))
);
INSERT OR IGNORE INTO DB_VERSION (VERSION) VALUES ('0.1.1');
