CREATE TABLE PAPER(
    PAPER_SK INTEGER,
    DOI VARCHAR(255),
    `VERSION` INTEGER NOT NULL,
    `URL` VARCHAR(500),
    TITLE varchar(255),
    TOPIC_PRIMARY_SK INTEGER,
    CONTENT_SK INTEGER,
    PRIMARY_AUTHOR_SK INTEGER,
    PRIMARY KEY PAPER_SK
);