CREATE TABLE IF NOT EXISTS PAPER_META(
    paper_id    TEXT    NOT NULL,
    version     INTEGER NOT NULL,
    url         TEXT,
    published   DATE,
    updated     DATE,
    categories  LIST,
    doi         TEXT,
    journal_ref TEXT,
    comment     TEXT,
    summary     TEXT,
    source      TEXT DEFAULT 'arxiv',
    pdf_path    TEXT,
    full_text   TEXT,
    downloaded_source BOOL DEFAULT 0,
    authors     LIST,
    tags        LIST,
    PRIMARY KEY (paper_id, version),
    FOREIGN KEY (paper_id, version) REFERENCES PAPER(paper_id, version) ON DELETE CASCADE
);
