CREATE TABLE IF NOT EXISTS PAPER_TO_AUTHOR(
    PTA_FK       INTEGER PRIMARY KEY AUTOINCREMENT,
    PAPER_ID     INTEGER NOT NULL,
    AUTHOR_FK    INTEGER NOT NULL,
    AUTHOR_INDEX INTEGER,
    CREATED_AT   TEXT NOT NULL DEFAULT (date('now')),
    UPDATED_AT   TEXT NOT NULL DEFAULT (date('now')),
    FOREIGN KEY (PAPER_ID)  REFERENCES PAPER(PAPER_ID)   ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_FK) REFERENCES AUTHOR(AUTHOR_FK)
);