CREATE TABLE IF NOT EXISTS PAPER_ROOTS (
    SOURCE_FK  INTEGER   PRIMARY KEY AUTOINCREMENT,
    SOURCE_ID  TEXT      NOT NULL UNIQUE,
    STATUS     TEXT      NOT NULL DEFAULT 'active',
    DELETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now')),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now'))
);
