CREATE TABLE IF NOT EXISTS PAPER_ROOTS (
    SOURCE_FK  INTEGER   PRIMARY KEY AUTOINCREMENT,
    SOURCE_ID  TEXT      NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT (date('now')),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT (date('now'))
);
