CREATE TABLE IF NOT EXISTS PAPER_TO_AUTHOR(
    PTA_FK INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    AUTHOR_FK INTEGER NOT NULL,
    author_index INTEGER,
    FOREIGN KEY (paper_id, version) REFERENCES PAPER(paper_id, version) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_FK) REFERENCES AUTHOR(AUTHOR_FK)
);
