CREATE TABLE PAPER_TO_TOPIC(
    PTT_SK INTEGER,
    TOPIC_SK INTEGER NOT NULL,
    PAPER_SK INTEGER NOT NULL,
    PRIMARY KEY PTT_SK,

    FOREIGN KEY (TOPIC_SK) REFERENCES TOPIC(TOPIC_SK),
    FOREIGN KEY (PAPER_SK) REFERENCES PAPER(PAPER_SK)
);