CREATE TABLE PAPER_TO_AUTHOR(
    PTA_SK INTEGER,
    AUTHOR_SK INTEGER NOT NULL,
    PAPER_SK INTEGER NOT NULL,
    AUTHOR_INDEX INTEGER, 
    PRIMARY KEY PTA_SK

    FOREIGN KEY (AUTHOR_SK) REFERENCES AUTHOR(AUTHOR_SK)
    FOREIGN KEY (PAPER_SK) REFERENCES PAPER(PAPER_SK)
);