CREATE TABLE IF NOT EXISTS PAPER(
    PAPER_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE_ID   TEXT    NOT NULL,
    VERSION     INTEGER NOT NULL,
    TITLE       TEXT    NOT NULL,
    CATEGORY    TEXT,
    HAS_PDF     BOOL NOT NULL DEFAULT 0,
    CREATED_AT  DATE NOT NULL DEFAULT (date('now')),
    UPDATED_AT  DATE NOT NULL DEFAULT (date('now')),
    SOURCE_FK   INTEGER NOT NULL,
    UNIQUE (SOURCE_ID, VERSION),
    FOREIGN KEY (SOURCE_FK) REFERENCES PAPER_ROOTS(SOURCE_FK) ON DELETE CASCADE
);
