CREATE TABLE IF NOT EXISTS PAPER_TO_TAG(
    PTT_FK     INTEGER PRIMARY KEY AUTOINCREMENT,
    PAPER_ID   INTEGER NOT NULL,
    SOURCE_ID  TEXT,
    VERSION    INTEGER,
    TAG_FK     INTEGER NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATED_AT DATETIME NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (PAPER_ID)           REFERENCES PAPER(PAPER_ID)           ON DELETE CASCADE,
    FOREIGN KEY (SOURCE_ID, VERSION) REFERENCES PAPER(SOURCE_ID, VERSION),
    FOREIGN KEY (TAG_FK)             REFERENCES TAG(TAG_FK)
);
