CREATE TABLE IF NOT EXISTS PAPER_META(
    PAPER_ID          INTEGER NOT NULL,
    URL               TEXT,
    PUBLISHED         DATE,
    UPDATED           DATE,
    CATEGORIES        LIST,
    DOI               TEXT,
    JOURNAL_REF       TEXT,
    COMMENT           TEXT,
    SUMMARY           TEXT,
    SOURCE            TEXT DEFAULT 'arxiv',
    PDF_PATH          TEXT,
    FULL_TEXT         TEXT,
    DOWNLOADED_SOURCE BOOL DEFAULT 0,
    AUTHORS           LIST,
    TAGS              LIST,
    CREATED_AT        TEXT NOT NULL DEFAULT (date('now')),
    UPDATED_AT        TEXT NOT NULL DEFAULT (date('now')),
    PRIMARY KEY (PAPER_ID),
    FOREIGN KEY (PAPER_ID) REFERENCES PAPER(PAPER_ID) ON DELETE CASCADE
);