CREATE TABLE IF NOT EXISTS PAPER_TO_TAG(
    PTT_FK INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    TAG_FK INTEGER NOT NULL,
    FOREIGN KEY (paper_id, version) REFERENCES PAPER(paper_id, version) ON DELETE CASCADE,
    FOREIGN KEY (TAG_FK) REFERENCES TAG(TAG_FK)
);
