CREATE TABLE PAPER_META(
    PAPER_META_SK INTEGER,
    PAPER_SK INTEGER,
    `URL` VARCHAR(500),
    PUBLISHED_DATE DATETIME,
    `UPDATE_DATE` DATETIME,
    JOURNAL_REF VARCHAR(255),
    USER_COMMENT varchar(1000),
    SUMMARY varchar(500),
    PRIMARY KEY PAPER_SK
    FOREIGN KEY (PAPER_SK) REFERENCES PAPER(PAPER_SK)
);