CREATE TABLE PROJECT_TO_PAPER(
    PROJECT_TO_PAPER_SK INTEGER,
    PROJECT_SK INTEGER,
    PAPER_SK INTEGER,
    PRIMARY KEY PROJECT_TO_PAPER_SK,
    FOREIGN KEY (PROJECT_SK) REFERENCES PROJECT(PROJECT_SK),
    FOREIGN KEY (PAPER_SK) REFERENCES PAPER(PAPER_SK)
)