CREATE TABLE IF NOT EXISTS PROJECT(
    PROJECT_FK   INTEGER NOT NULL,
    NAME         TEXT    NOT NULL,
    DESCRIPTION  TEXT    DEFAULT '',
    COLOR        INTEGER,
    STATUS       TEXT    NOT NULL DEFAULT 'active',
    CREATED_AT   TIMESTAMP,
    UPDATED_AT   TIMESTAMP,
    ARCHIVED_AT  TIMESTAMP,
    PRIMARY KEY (PROJECT_FK)
);