CREATE TABLE IF NOT EXISTS PROJECT(
    PROJECT_FK INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL DEFAULT (date('now')),
    UPDATED_AT TEXT NOT NULL DEFAULT (date('now')),
    PRIMARY KEY (PROJECT_FK)
);
