CREATE TABLE IF NOT EXISTS PROJECT_TO_TAG(
    PROJECT_TO_TAG_FK INTEGER NOT NULL,
    PROJECT_FK INTEGER NOT NULL,
    TAG_FK INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now')),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (PROJECT_TO_TAG_FK),
    FOREIGN KEY (PROJECT_FK) REFERENCES PROJECT(PROJECT_FK),
    FOREIGN KEY (TAG_FK) REFERENCES TAG(TAG_FK)
);
