CREATE TABLE IF NOT EXISTS PROJECT_TO_PAPER(
    PROJECT_TO_PAPER_FK INTEGER NOT NULL,
    PROJECT_FK INTEGER NOT NULL,
    paper_id TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL DEFAULT (date('now')),
    UPDATED_AT TEXT NOT NULL DEFAULT (date('now')),
    PRIMARY KEY (PROJECT_TO_PAPER_FK),
    FOREIGN KEY (PROJECT_FK) REFERENCES PROJECT(PROJECT_FK),
    FOREIGN KEY (paper_id) REFERENCES paper_roots(paper_id) ON DELETE CASCADE
);
