-- SOURCE_FK references paper_roots, so a project membership row covers all versions of a paper.
CREATE TABLE IF NOT EXISTS PROJECT_TO_PAPER(
    PROJECT_TO_PAPER_FK INTEGER NOT NULL,
    PROJECT_FK  INTEGER NOT NULL,
    SOURCE_FK   INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL DEFAULT (date('now')),
    UPDATED_AT TEXT NOT NULL DEFAULT (date('now')),
    PRIMARY KEY (PROJECT_TO_PAPER_FK),
    FOREIGN KEY (PROJECT_FK) REFERENCES PROJECT(PROJECT_FK),
    FOREIGN KEY (SOURCE_FK) REFERENCES paper_roots(SOURCE_FK) ON DELETE CASCADE
);
