CREATE TABLE IF NOT EXISTS SEARCH_HISTORY (
    HISTORY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TERM       TEXT      NOT NULL UNIQUE,
    USE_COUNT  INTEGER   NOT NULL DEFAULT 1,
    LAST_USED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_search_history_term ON SEARCH_HISTORY (TERM);
