CREATE TABLE IF NOT EXISTS SEARCH_STATE (
    ID           INTEGER   PRIMARY KEY CHECK (ID = 1),
    CLAUSES_JSON TEXT      NOT NULL,
    SOURCE       TEXT      NOT NULL,
    MAX_RESULTS  INTEGER   NOT NULL DEFAULT 25,
    RESULTS_JSON TEXT      NOT NULL,
    SAVED_IDS_JSON TEXT    NOT NULL,
    UPDATED_AT   TIMESTAMP NOT NULL DEFAULT (datetime('now'))
);
