CREATE TABLE IF NOT EXISTS TAG(
    TAG_FK INTEGER PRIMARY KEY AUTOINCREMENT,
    TAG TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now')),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT (datetime('now'))
);
