"""Tests for sources/pdf_metadata.py."""

from __future__ import annotations

import datetime
import hashlib
from pathlib import Path
from unittest.mock import MagicMock, patch, PropertyMock

import pytest

from sources.base import PaperMetadata
from sources.pdf_metadata import (
    _looks_autogenerated,
    _extract_doi,
    _extract_arxiv_id,
    _title_similarity,
    extract_pdf_metadata,
    resolve_pdf_metadata,
)


# ---------------------------------------------------------------------------
# _looks_autogenerated
# ---------------------------------------------------------------------------

class TestLooksAutogenerated:
    def test_microsoft_word(self):
        assert _looks_autogenerated("Microsoft Word - Document1")

    def test_untitled(self):
        assert _looks_autogenerated("Untitled")

    def test_powerpoint(self):
        assert _looks_autogenerated("PowerPoint Presentation")

    def test_blank(self):
        assert _looks_autogenerated("   ")

    def test_real_title(self):
        assert not _looks_autogenerated("Attention Is All You Need")

    def test_case_insensitive(self):
        assert _looks_autogenerated("microsoft word doc")


# ---------------------------------------------------------------------------
# _extract_doi
# ---------------------------------------------------------------------------

class TestExtractDoi:
    def test_extracts_standard_doi(self):
        text = "See doi: 10.1234/journal.abc for details."
        assert _extract_doi(text) == "10.1234/journal.abc"

    def test_strips_trailing_punctuation(self):
        text = "Published at 10.1234/xyz.456."
        assert _extract_doi(text) == "10.1234/xyz.456"

    def test_strips_trailing_paren(self):
        text = "Reference (10.1234/foo)"
        assert _extract_doi(text) == "10.1234/foo"

    def test_extracts_arxiv_doi(self):
        text = "10.48550/arXiv.2204.12985 was accepted."
        assert _extract_doi(text) == "10.48550/arXiv.2204.12985"

    def test_returns_none_when_absent(self):
        assert _extract_doi("No DOI in this text.") is None

    def test_requires_four_digit_registrant(self):
        assert _extract_doi("10.123/short") is None


# ---------------------------------------------------------------------------
# _extract_arxiv_id
# ---------------------------------------------------------------------------

class TestExtractArxivId:
    def test_extracts_standard_id(self):
        assert _extract_arxiv_id("arXiv:2411.10406v2") == "2411.10406v2"

    def test_extracts_id_without_version(self):
        assert _extract_arxiv_id("arXiv:2204.12985") == "2204.12985"

    def test_case_insensitive(self):
        assert _extract_arxiv_id("arxiv:2204.12985v1") == "2204.12985v1"

    def test_extracts_from_surrounding_text(self):
        assert _extract_arxiv_id("Submitted to arXiv:2411.10406v2 for review") == "2411.10406v2"

    def test_returns_none_when_absent(self):
        assert _extract_arxiv_id("No arXiv ID here.") is None

    def test_five_digit_id(self):
        assert _extract_arxiv_id("arXiv:2204.12345v1") == "2204.12345v1"


# ---------------------------------------------------------------------------
# _title_similarity
# ---------------------------------------------------------------------------

class TestTitleSimilarity:
    def test_identical_titles(self):
        assert _title_similarity("Attention Is All You Need", "Attention Is All You Need") == 1.0

    def test_completely_different(self):
        assert _title_similarity("Alpha Beta Gamma", "Delta Epsilon Zeta") == 0.0

    def test_partial_overlap(self):
        score = _title_similarity("Deep Learning Models", "Deep Neural Learning")
        assert 0.0 < score < 1.0

    def test_case_insensitive(self):
        assert _title_similarity("Hello World", "hello world") == 1.0

    def test_empty_strings(self):
        assert _title_similarity("", "anything") == 0.0


# ---------------------------------------------------------------------------
# extract_pdf_metadata
# ---------------------------------------------------------------------------

def _make_reader(title=None, author=None, creation_date=None, first_page_text=""):
    """Build a minimal PdfReader mock."""
    reader = MagicMock()
    meta = {}
    if title:
        meta["/Title"] = title
    if author:
        meta["/Author"] = author
    if creation_date:
        meta["/CreationDate"] = creation_date
    reader.metadata = meta

    page = MagicMock()
    page.extract_text.return_value = first_page_text
    reader.pages = [page]
    return reader


class TestExtractPdfMetadata:
    def test_extracts_title(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader(title="My Paper")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["title"] == "My Paper"

    def test_filters_autogenerated_title(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader(title="Microsoft Word - doc")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["title"] is None

    def test_extracts_author(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader(author="Jane Doe")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["authors"] == "Jane Doe"

    def test_extracts_doi_from_first_page(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(first_page_text="DOI: 10.1234/test.123")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["doi"] == "10.1234/test.123"

    def test_no_doi_when_absent(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader()):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["doi"] is None

    def test_extracts_year_from_creation_date(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(creation_date="D:20210315120000")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["year"] == 2021

    def test_abstract_always_none(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(title="T", first_page_text="Abstract: blah")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["abstract"] is None

    def test_rejects_implausible_year(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(creation_date="D:18990101")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["year"] is None

    def test_extracts_arxiv_id_from_first_page(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(first_page_text="arXiv:2411.10406v2")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["arxiv_id"] == "2411.10406v2"

    def test_no_arxiv_id_when_absent(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader()):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["arxiv_id"] is None

    def test_missing_metadata_returns_nones(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader()):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result == {"title": None, "authors": None, "doi": None, "arxiv_id": None, "year": None, "abstract": None}


# ---------------------------------------------------------------------------
# resolve_pdf_metadata
# ---------------------------------------------------------------------------

class TestResolvePdfMetadata:
    def _patch_extract(self, **kwargs):
        defaults = {"title": None, "authors": None, "doi": None, "arxiv_id": None, "year": None, "abstract": None}
        defaults.update(kwargs)
        return patch("sources.pdf_metadata.extract_pdf_metadata", return_value=defaults)

    def test_arxiv_id_resolved_before_doi(self):
        expected = PaperMetadata(
            paper_id="2411.10406", version=2, title="Quantum Paper", authors=["A"],
            published=datetime.date(2024, 11, 15), summary="", source="arxiv",
        )
        with self._patch_extract(arxiv_id="2411.10406v2"):
            with patch("sources.pdf_metadata.ArxivSource") as mock_cls:
                mock_cls.return_value.fetch_by_id.return_value = expected
                result = resolve_pdf_metadata("/fake/path.pdf")
        mock_cls.return_value.fetch_by_id.assert_called_once_with("2411.10406v2")
        assert result.source == "arxiv"

    def test_doi_found_calls_resolve_doi(self):
        expected = PaperMetadata(
            paper_id="2204.12985", version=1, title="Resolved", authors=["A"],
            published=datetime.date(2022, 4, 1), summary="", source="arxiv",
        )
        with self._patch_extract(doi="10.48550/arXiv.2204.12985"):
            with patch("sources.pdf_metadata.resolve_doi", return_value=expected) as mock_resolve:
                result = resolve_pdf_metadata("/fake/path.pdf")
        mock_resolve.assert_called_once_with("10.48550/arXiv.2204.12985")
        assert result.paper_id == "2204.12985"

    def test_doi_resolution_failure_falls_through_to_title_search(self):
        crossref_result = PaperMetadata(
            paper_id="10.9999/x", version=1, title="Title Match", authors=[],
            published=datetime.date(2020, 1, 1), summary="", source="crossref",
        )
        with self._patch_extract(doi="10.9999/bad", title="Title Match"):
            with patch("sources.pdf_metadata.resolve_doi", side_effect=ValueError("not found")):
                with patch("sources.pdf_metadata.search_by_title", return_value=[crossref_result]):
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.source == "crossref"

    def test_no_doi_uses_title_search(self):
        crossref_result = PaperMetadata(
            paper_id="10.1234/xyz", version=1, title="My Paper", authors=[],
            published=datetime.date(2021, 6, 1), summary="", source="crossref",
        )
        with self._patch_extract(title="My Paper"):
            with patch("sources.pdf_metadata.search_by_title", return_value=[crossref_result]):
                result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.title == "My Paper"

    def test_all_resolution_fails_returns_partial_record(self):
        with self._patch_extract(title="Some Paper", authors="Jane Doe", year=2019):
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = b"fake pdf bytes"
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.source == "pdf"
        assert result.title == "Some Paper"
        assert result.published == datetime.date(2019, 1, 1)

    def test_partial_record_splits_authors_on_semicolon(self):
        with self._patch_extract(authors="Jane Doe; John Smith"):
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = b"x"
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.authors == ["Jane Doe", "John Smith"]

    def test_partial_record_paper_id_is_pdf_prefixed(self):
        with self._patch_extract():
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = b"content"
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.paper_id.startswith("pdf:")

    def test_partial_record_id_is_deterministic(self):
        content = b"stable pdf bytes"
        expected_id = "pdf:" + hashlib.sha256(content).hexdigest()[:16]
        with self._patch_extract():
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = content
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.paper_id == expected_id


# ---------------------------------------------------------------------------
# Integration tests — real PDF files in tests/test_file/
# Network calls are mocked; pypdf reads the actual files.
# ---------------------------------------------------------------------------

TEST_PDF_MULTI_AUTHOR  = Path(__file__).parent / "test_file" / "2411.10406v2.pdf"
TEST_PDF_EMBEDDED_META = Path(__file__).parent / "test_file" / "2604.21547v1.pdf"
TEST_PDF_JUNK_AUTHOR   = Path(__file__).parent / "test_file" / "2604.00068v2.pdf"


@pytest.fixture
def real_pdf():
    if not TEST_PDF_MULTI_AUTHOR.exists():
        pytest.skip("test PDF not present")
    return str(TEST_PDF_MULTI_AUTHOR)


@pytest.fixture
def pdf_embedded_meta():
    if not TEST_PDF_EMBEDDED_META.exists():
        pytest.skip("test PDF not present")
    return str(TEST_PDF_EMBEDDED_META)


@pytest.fixture
def pdf_junk_author():
    if not TEST_PDF_JUNK_AUTHOR.exists():
        pytest.skip("test PDF not present")
    return str(TEST_PDF_JUNK_AUTHOR)


class TestExtractPdfMetadataReal:
    def test_title_extracted_from_first_page_text(self, real_pdf):
        result = extract_pdf_metadata(real_pdf)
        assert result["title"] == "How to Build a Quantum Supercomputer: Scaling from Hundreds to Millions of Qubits"

    def test_arxiv_id_found_in_first_page(self, real_pdf):
        result = extract_pdf_metadata(real_pdf)
        assert result["arxiv_id"] == "2411.10406v2"

    def test_authors_is_none_because_embedded_field_is_empty(self, real_pdf):
        result = extract_pdf_metadata(real_pdf)
        assert result["authors"] is None

    def test_doi_is_none_because_not_in_first_page_text(self, real_pdf):
        result = extract_pdf_metadata(real_pdf)
        assert result["doi"] is None

    def test_year_extracted_from_creation_date(self, real_pdf):
        result = extract_pdf_metadata(real_pdf)
        assert result["year"] == 2025

    def test_abstract_is_always_none(self, real_pdf):
        result = extract_pdf_metadata(real_pdf)
        assert result["abstract"] is None


class TestResolvePdfMetadataReal:
    def test_resolves_via_arxiv_id(self, real_pdf):
        with patch("sources.pdf_metadata.ArxivSource") as mock_cls:
            expected = PaperMetadata(
                paper_id="2411.10406", version=2, title="Quantum Supercomputer Paper",
                authors=["A"], published=datetime.date(2024, 11, 15), summary="", source="arxiv",
            )
            mock_cls.return_value.fetch_by_id.return_value = expected
            result = resolve_pdf_metadata(real_pdf)
        mock_cls.return_value.fetch_by_id.assert_called_once_with("2411.10406v2")
        assert result.source == "arxiv"

    def test_falls_through_to_partial_when_arxiv_fails(self, real_pdf):
        with patch("sources.pdf_metadata.ArxivSource") as mock_cls:
            mock_cls.return_value.fetch_by_id.side_effect = ValueError("not found")
            with patch("sources.pdf_metadata.search_by_title", return_value=[]):
                result = resolve_pdf_metadata(real_pdf)
        assert result.source == "pdf"
        assert "Quantum Supercomputer" in result.title


# 2604.21547v1.pdf — embedded title + author, single author, no creation date

class TestExtractPdfMetadataEmbedded:
    def test_title_from_embedded_field(self, pdf_embedded_meta):
        result = extract_pdf_metadata(pdf_embedded_meta)
        assert "Yang-Baxter" in result["title"]

    def test_author_from_embedded_field(self, pdf_embedded_meta):
        result = extract_pdf_metadata(pdf_embedded_meta)
        assert result["authors"] == "Vinayak M. Kulkarni"

    def test_no_doi(self, pdf_embedded_meta):
        result = extract_pdf_metadata(pdf_embedded_meta)
        assert result["doi"] is None

    def test_no_year_when_creation_date_absent(self, pdf_embedded_meta):
        result = extract_pdf_metadata(pdf_embedded_meta)
        assert result["year"] is None


class TestResolvePdfMetadataEmbedded:
    def test_arxiv_id_found_in_first_page(self, pdf_embedded_meta):
        result = extract_pdf_metadata(pdf_embedded_meta)
        assert result["arxiv_id"] == "2604.21547v1"

    def test_resolves_via_arxiv_id(self, pdf_embedded_meta):
        with patch("sources.pdf_metadata.ArxivSource") as mock_cls:
            expected = PaperMetadata(
                paper_id="2604.21547", version=1, title="Yang-Baxter Paper",
                authors=["Vinayak M. Kulkarni"], published=datetime.date(2026, 4, 23),
                summary="", source="arxiv",
            )
            mock_cls.return_value.fetch_by_id.return_value = expected
            result = resolve_pdf_metadata(pdf_embedded_meta)
        assert result.source == "arxiv"


# 2604.00068v2.pdf — no embedded title, OS-generated junk author, blank-line separator

class TestExtractPdfMetadataJunkAuthor:
    def test_title_extracted_from_text_stops_at_blank_line(self, pdf_junk_author):
        result = extract_pdf_metadata(pdf_junk_author)
        assert "Chandrasekhar" in result["title"]
        assert "Fikret" not in result["title"]
        assert "Email" not in result["title"]

    def test_junk_author_filtered_out(self, pdf_junk_author):
        result = extract_pdf_metadata(pdf_junk_author)
        assert result["authors"] is None

    def test_year_from_creation_date(self, pdf_junk_author):
        result = extract_pdf_metadata(pdf_junk_author)
        assert result["year"] == 2025

    def test_no_doi(self, pdf_junk_author):
        result = extract_pdf_metadata(pdf_junk_author)
        assert result["doi"] is None


class TestResolvePdfMetadataJunkAuthor:
    def test_title_search_uses_text_extracted_title(self, pdf_junk_author):
        with patch("sources.pdf_metadata.search_by_title", return_value=[]) as mock_search:
            resolve_pdf_metadata(pdf_junk_author)
        mock_search.assert_called_once()
        assert "Chandrasekhar" in mock_search.call_args[0][0]

    def test_partial_record_has_no_junk_authors(self, pdf_junk_author):
        with patch("sources.pdf_metadata.search_by_title", return_value=[]):
            result = resolve_pdf_metadata(pdf_junk_author)
        assert result.authors == []
