"""Tests for sources/pdf_metadata.py."""

from __future__ import annotations

import datetime
import hashlib
from pathlib import Path
from unittest.mock import MagicMock, patch, PropertyMock

import pytest

from sources.base import PaperMetadata
from sources.pdf_metadata import (
    _looks_autogenerated,
    _extract_doi,
    _title_similarity,
    extract_pdf_metadata,
    resolve_pdf_metadata,
)


# ---------------------------------------------------------------------------
# _looks_autogenerated
# ---------------------------------------------------------------------------

class TestLooksAutogenerated:
    def test_microsoft_word(self):
        assert _looks_autogenerated("Microsoft Word - Document1")

    def test_untitled(self):
        assert _looks_autogenerated("Untitled")

    def test_powerpoint(self):
        assert _looks_autogenerated("PowerPoint Presentation")

    def test_blank(self):
        assert _looks_autogenerated("   ")

    def test_real_title(self):
        assert not _looks_autogenerated("Attention Is All You Need")

    def test_case_insensitive(self):
        assert _looks_autogenerated("microsoft word doc")


# ---------------------------------------------------------------------------
# _extract_doi
# ---------------------------------------------------------------------------

class TestExtractDoi:
    def test_extracts_standard_doi(self):
        text = "See doi: 10.1234/journal.abc for details."
        assert _extract_doi(text) == "10.1234/journal.abc"

    def test_strips_trailing_punctuation(self):
        text = "Published at 10.1234/xyz.456."
        assert _extract_doi(text) == "10.1234/xyz.456"

    def test_strips_trailing_paren(self):
        text = "Reference (10.1234/foo)"
        assert _extract_doi(text) == "10.1234/foo"

    def test_extracts_arxiv_doi(self):
        text = "10.48550/arXiv.2204.12985 was accepted."
        assert _extract_doi(text) == "10.48550/arXiv.2204.12985"

    def test_returns_none_when_absent(self):
        assert _extract_doi("No DOI in this text.") is None

    def test_requires_four_digit_registrant(self):
        assert _extract_doi("10.123/short") is None


# ---------------------------------------------------------------------------
# _title_similarity
# ---------------------------------------------------------------------------

class TestTitleSimilarity:
    def test_identical_titles(self):
        assert _title_similarity("Attention Is All You Need", "Attention Is All You Need") == 1.0

    def test_completely_different(self):
        assert _title_similarity("Alpha Beta Gamma", "Delta Epsilon Zeta") == 0.0

    def test_partial_overlap(self):
        score = _title_similarity("Deep Learning Models", "Deep Neural Learning")
        assert 0.0 < score < 1.0

    def test_case_insensitive(self):
        assert _title_similarity("Hello World", "hello world") == 1.0

    def test_empty_strings(self):
        assert _title_similarity("", "anything") == 0.0


# ---------------------------------------------------------------------------
# extract_pdf_metadata
# ---------------------------------------------------------------------------

def _make_reader(title=None, author=None, creation_date=None, first_page_text=""):
    """Build a minimal PdfReader mock."""
    reader = MagicMock()
    meta = {}
    if title:
        meta["/Title"] = title
    if author:
        meta["/Author"] = author
    if creation_date:
        meta["/CreationDate"] = creation_date
    reader.metadata = meta

    page = MagicMock()
    page.extract_text.return_value = first_page_text
    reader.pages = [page]
    return reader


class TestExtractPdfMetadata:
    def test_extracts_title(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader(title="My Paper")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["title"] == "My Paper"

    def test_filters_autogenerated_title(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader(title="Microsoft Word - doc")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["title"] is None

    def test_extracts_author(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader(author="Jane Doe")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["authors"] == "Jane Doe"

    def test_extracts_doi_from_first_page(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(first_page_text="DOI: 10.1234/test.123")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["doi"] == "10.1234/test.123"

    def test_no_doi_when_absent(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader()):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["doi"] is None

    def test_extracts_year_from_creation_date(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(creation_date="D:20210315120000")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["year"] == 2021

    def test_abstract_always_none(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(title="T", first_page_text="Abstract: blah")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["abstract"] is None

    def test_rejects_implausible_year(self):
        with patch("sources.pdf_metadata.PdfReader",
                   return_value=_make_reader(creation_date="D:18990101")):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result["year"] is None

    def test_missing_metadata_returns_nones(self):
        with patch("sources.pdf_metadata.PdfReader", return_value=_make_reader()):
            result = extract_pdf_metadata("/fake/path.pdf")
        assert result == {"title": None, "authors": None, "doi": None, "year": None, "abstract": None}


# ---------------------------------------------------------------------------
# resolve_pdf_metadata
# ---------------------------------------------------------------------------

class TestResolvePdfMetadata:
    def _patch_extract(self, **kwargs):
        defaults = {"title": None, "authors": None, "doi": None, "year": None, "abstract": None}
        defaults.update(kwargs)
        return patch("sources.pdf_metadata.extract_pdf_metadata", return_value=defaults)

    def test_doi_found_calls_resolve_doi(self):
        expected = PaperMetadata(
            paper_id="2204.12985", version=1, title="Resolved", authors=["A"],
            published=datetime.date(2022, 4, 1), summary="", source="arxiv",
        )
        with self._patch_extract(doi="10.48550/arXiv.2204.12985"):
            with patch("sources.pdf_metadata.resolve_doi", return_value=expected) as mock_resolve:
                result = resolve_pdf_metadata("/fake/path.pdf")
        mock_resolve.assert_called_once_with("10.48550/arXiv.2204.12985")
        assert result.paper_id == "2204.12985"

    def test_doi_resolution_failure_falls_through_to_title_search(self):
        crossref_result = PaperMetadata(
            paper_id="10.9999/x", version=1, title="Title Match", authors=[],
            published=datetime.date(2020, 1, 1), summary="", source="crossref",
        )
        with self._patch_extract(doi="10.9999/bad", title="Title Match"):
            with patch("sources.pdf_metadata.resolve_doi", side_effect=ValueError("not found")):
                with patch("sources.pdf_metadata.search_by_title", return_value=[crossref_result]):
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.source == "crossref"

    def test_no_doi_uses_title_search(self):
        crossref_result = PaperMetadata(
            paper_id="10.1234/xyz", version=1, title="My Paper", authors=[],
            published=datetime.date(2021, 6, 1), summary="", source="crossref",
        )
        with self._patch_extract(title="My Paper"):
            with patch("sources.pdf_metadata.search_by_title", return_value=[crossref_result]):
                result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.title == "My Paper"

    def test_all_resolution_fails_returns_partial_record(self):
        with self._patch_extract(title="Some Paper", authors="Jane Doe", year=2019):
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = b"fake pdf bytes"
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.source == "pdf"
        assert result.title == "Some Paper"
        assert result.published == datetime.date(2019, 1, 1)

    def test_partial_record_splits_authors_on_semicolon(self):
        with self._patch_extract(authors="Jane Doe; John Smith"):
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = b"x"
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.authors == ["Jane Doe", "John Smith"]

    def test_partial_record_paper_id_is_pdf_prefixed(self):
        with self._patch_extract():
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = b"content"
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.paper_id.startswith("pdf:")

    def test_partial_record_id_is_deterministic(self):
        content = b"stable pdf bytes"
        expected_id = "pdf:" + hashlib.sha256(content).hexdigest()[:16]
        with self._patch_extract():
            with patch("sources.pdf_metadata._try_crossref_title", return_value=None):
                with patch("sources.pdf_metadata.Path") as mock_path:
                    mock_path.return_value.read_bytes.return_value = content
                    result = resolve_pdf_metadata("/fake/path.pdf")
        assert result.paper_id == expected_id
