"""PDF metadata extraction pipeline.

Extraction chain (each stage falls through on failure):
    pypdf embedded fields
        -> first-page text title heuristic (when embedded title is absent)
        -> arXiv ID from first-page text   -> ArxivSource.fetch_by_id()
        -> DOI regex from first-page text  -> resolve_doi()
            -> CrossRef title search
                -> partial record (caller must prompt user to fill missing fields)
"""

from __future__ import annotations

import datetime
import hashlib
import re
from pathlib import Path
from typing import Optional

from pypdf import PdfReader

from .arxiv_source import ArxivSource
from .base import PaperMetadata
from .crossref_source import search_by_title
from .doi_resolve import resolve_doi

_DOI_RE = re.compile(r"\b10\.\d{4,}/\S+")
_ARXIV_ID_RE = re.compile(r"arXiv:(\d{4}\.\d{4,5}(?:v\d+)?)", re.IGNORECASE)

_AUTOGENERATED_TITLE_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in [r"^Microsoft Word", r"^Untitled", r"^\s*$", r"^PowerPoint"]
]

_JUNK_AUTHOR_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in [r"\bWindows\b", r"^User$", r"^Admin$", r"^Benutzer$", r"^Utilisateur$"]
]


def _looks_autogenerated(title: str) -> bool:
    return any(p.match(title) for p in _AUTOGENERATED_TITLE_PATTERNS)


def _looks_junk_author(author: str) -> bool:
    return any(p.search(author) for p in _JUNK_AUTHOR_PATTERNS)


def _extract_doi(text: str) -> Optional[str]:
    m = _DOI_RE.search(text)
    return m.group(0).rstrip(".,)") if m else None


def _extract_arxiv_id(text: str) -> Optional[str]:
    m = _ARXIV_ID_RE.search(text)
    return m.group(1) if m else None


def _title_similarity(a: str, b: str) -> float:
    """Jaccard word-overlap between two titles (case-insensitive)."""
    words_a = set(re.findall(r"\w+", a.lower()))
    words_b = set(re.findall(r"\w+", b.lower()))
    if not words_a or not words_b:
        return 0.0
    return len(words_a & words_b) / len(words_a | words_b)


def _try_crossref_title(title: str) -> PaperMetadata | None:
    """Search CrossRef by title via CrossRefSource; rejects results with low similarity."""
    candidates = search_by_title(title, limit=3)
    for candidate in candidates:
        if candidate.title and _title_similarity(title, candidate.title) >= 0.5:
            # Upgrade to full resolution if we have a DOI (gets arXiv record when available)
            if candidate.doi:
                try:
                    return resolve_doi(candidate.doi)
                except Exception:
                    pass
            return candidate
    return None


_AUTHOR_LINE_RE = re.compile(r"\b[A-Z][a-z]+,\s*\d")


def _extract_title_from_text(text: str) -> Optional[str]:
    """Heuristically extract a title from first-page text.

    Stops at the first blank line after content (title/body separator common
    in single-author papers) or at the first line matching an author-list
    pattern (surname followed by affiliation superscript, e.g. 'Mohseni,1').
    Caps at 3 lines to avoid grabbing too much.
    """
    title_lines: list[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped:
            if title_lines:
                break  # blank line after content — title block ended
            continue   # leading blank, skip
        if _AUTHOR_LINE_RE.search(stripped):
            break
        title_lines.append(stripped)
        if len(title_lines) == 3:
            break
    if not title_lines:
        return None
    return " ".join(title_lines)


def _pdf_source_id(pdf_path: str) -> str:
    digest = hashlib.sha256(Path(pdf_path).read_bytes()).hexdigest()[:16]
    return f"local:{digest}"


def extract_pdf_metadata(pdf_path: str) -> dict:
    """Extract raw metadata from a PDF's embedded fields and first-page text.

    Returns a dict with keys: title, authors, doi, year, abstract.
    Values are None when not found. `abstract` is always None at this stage —
    the PDF /Subject field is not a reliable abstract source.
    """
    reader = PdfReader(pdf_path)
    meta = reader.metadata or {}

    title: Optional[str] = meta.get("/Title") or None
    if title and _looks_autogenerated(title):
        title = None

    authors: Optional[str] = meta.get("/Author") or None
    if authors and _looks_junk_author(authors):
        authors = None

    doi: Optional[str] = None
    arxiv_id: Optional[str] = None
    first_page_text = ""
    if reader.pages:
        first_page_text = reader.pages[0].extract_text() or ""
        doi = _extract_doi(first_page_text)
        arxiv_id = _extract_arxiv_id(first_page_text)

    if not title and first_page_text:
        title = _extract_title_from_text(first_page_text)

    year: Optional[int] = None
    date_str = meta.get("/CreationDate") or meta.get("/ModDate")
    if date_str:
        m = re.search(r"(\d{4})", str(date_str))
        if m:
            candidate = int(m.group(1))
            if 1900 <= candidate <= datetime.date.today().year + 1:
                year = candidate

    return {
        "title": title,
        "authors": authors,
        "doi": doi,
        "arxiv_id": arxiv_id,
        "year": year,
        "abstract": None,
    }


def resolve_pdf_metadata(
    pdf_path: str,
) -> tuple[PaperMetadata, tuple[str, int] | None]:
    """Run the full metadata pipeline for a PDF file.

    Returns ``(meta, external_identity)`` where:
      - ``meta`` is a PaperMetadata with a ``local:<sha256>`` source_id so the
        imported paper defaults to a local identity regardless of where it was
        sourced. Metadata fields (title, authors, etc.) are enriched from
        arXiv/CrossRef when an ID is found in the first-page text.
      - ``external_identity`` is ``(source_id, version)`` of the upstream
        record we matched (e.g. ``("arxiv:2204.12985", 4)`` or
        ``("doi:10.1234/xyz", 1)``) when enrichment succeeded, else ``None``.
        Callers that have DB access can use this to dedupe against existing
        paper roots — see ``service/paper.py:import_pdf``.

    Resolution order for metadata enrichment:
      1. arXiv ID found in first-page text  -> ArxivSource.fetch_by_id()
      2. DOI found in first-page text       -> resolve_doi()
      3. Title (embedded or text heuristic) -> CrossRef title search
      4. Partial record from whatever was extracted (caller prompts for missing fields)

    Raises FileNotFoundError if the path does not exist, or pypdf errors on corrupt PDFs.
    """
    raw = extract_pdf_metadata(pdf_path)
    local_id = _pdf_source_id(pdf_path)

    enriched: PaperMetadata | None = None

    if raw["arxiv_id"]:
        try:
            enriched = ArxivSource().fetch_by_id(raw["arxiv_id"])
        except Exception:
            pass

    if not enriched and raw["doi"]:
        try:
            enriched = resolve_doi(raw["doi"])
        except ValueError:
            pass

    if not enriched and raw["title"]:
        enriched = _try_crossref_title(raw["title"])

    if enriched:
        external = (
            (enriched.source_id, enriched.version)
            if enriched.source_id
            else None
        )
        meta = PaperMetadata(
            source_id=local_id,
            version=1,
            title=enriched.title or raw["title"] or "",
            authors=enriched.authors,
            published=enriched.published,
            summary=enriched.summary,
            doi=enriched.doi,
            url=enriched.url,
            category=enriched.category,
            source="pdf",
        )
        return meta, external

    authors: list[str] = []
    if raw["authors"]:
        # Split on semicolons first, then commas — handles "Doe, John; Smith, Jane"
        parts = re.split(r";", raw["authors"])
        authors = [p.strip() for p in parts if p.strip()]

    pub_date = datetime.date.today()
    if raw["year"]:
        pub_date = datetime.date(raw["year"], 1, 1)

    meta = PaperMetadata(
        source_id=local_id,
        version=1,
        title=raw["title"] or "",
        authors=authors,
        published=pub_date,
        summary="",
        source="pdf",
    )
    return meta, None
