"""PDF metadata extraction pipeline.

Extraction chain (each stage falls through on failure):
    pypdf embedded fields
        -> DOI regex from first-page text  -> resolve_doi()
            -> CrossRef title search
                -> partial record (caller must prompt user to fill missing fields)
"""

from __future__ import annotations

import datetime
import hashlib
import re
from pathlib import Path
from typing import Optional
from urllib.parse import quote_plus

from pypdf import PdfReader

from .base import PaperMetadata
from .doi_resolve import _fetch_url, resolve_doi

_DOI_RE = re.compile(r"\b10\.\d{4,}/\S+")

_AUTOGENERATED_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in [r"^Microsoft Word", r"^Untitled", r"^\s*$", r"^PowerPoint"]
]


def _looks_autogenerated(title: str) -> bool:
    return any(p.match(title) for p in _AUTOGENERATED_PATTERNS)


def _extract_doi(text: str) -> Optional[str]:
    m = _DOI_RE.search(text)
    return m.group(0).rstrip(".,)") if m else None


def _title_similarity(a: str, b: str) -> float:
    """Jaccard word-overlap between two titles (case-insensitive)."""
    words_a = set(re.findall(r"\w+", a.lower()))
    words_b = set(re.findall(r"\w+", b.lower()))
    if not words_a or not words_b:
        return 0.0
    return len(words_a & words_b) / len(words_a | words_b)


def _try_crossref_title(title: str) -> PaperMetadata | None:
    """Search CrossRef by title; rejects results with low similarity to the query."""
    try:
        data = _fetch_url(
            f"https://api.crossref.org/works?query.title={quote_plus(title)}&rows=1"
        )
    except Exception:
        return None

    items = data.get("message", {}).get("items", [])
    if not items:
        return None

    item = items[0]
    item_title = (item.get("title") or [""])[0]
    if not item_title or _title_similarity(title, item_title) < 0.5:
        return None

    doi = item.get("DOI")
    if doi:
        try:
            return resolve_doi(doi)
        except Exception:
            pass

    authors: list[str] = []
    for a in item.get("author", []):
        given = a.get("given", "")
        family = a.get("family", "")
        name = f"{given} {family}".strip()
        if name:
            authors.append(name)

    pub_date = datetime.date.today()
    dp = (item.get("published") or {}).get("date-parts", [[]])
    if dp and dp[0]:
        parts = dp[0]
        try:
            pub_date = datetime.date(
                parts[0],
                parts[1] if len(parts) > 1 else 1,
                parts[2] if len(parts) > 2 else 1,
            )
        except (ValueError, TypeError):
            pass

    abstract = re.sub(r"<[^>]+>", "", item.get("abstract") or "").strip()
    journal = (item.get("container-title") or [""])[0]

    return PaperMetadata(
        paper_id=doi or f"pdf:{hashlib.sha256(item_title.encode()).hexdigest()[:16]}",
        version=1,
        title=item_title,
        authors=authors,
        published=pub_date,
        summary=abstract,
        category=journal or None,
        doi=doi,
        url=item.get("URL") or (f"https://doi.org/{doi}" if doi else None),
        source="crossref",
    )


def _pdf_paper_id(pdf_path: str) -> str:
    digest = hashlib.sha256(Path(pdf_path).read_bytes()).hexdigest()[:16]
    return f"pdf:{digest}"


def extract_pdf_metadata(pdf_path: str) -> dict:
    """Extract raw metadata from a PDF's embedded fields and first-page text.

    Returns a dict with keys: title, authors, doi, year, abstract.
    Values are None when not found. `abstract` is always None at this stage —
    the PDF /Subject field is not a reliable abstract source.
    """
    reader = PdfReader(pdf_path)
    meta = reader.metadata or {}

    title: Optional[str] = meta.get("/Title") or None
    if title and _looks_autogenerated(title):
        title = None

    authors: Optional[str] = meta.get("/Author") or None

    doi: Optional[str] = None
    if reader.pages:
        first_page_text = reader.pages[0].extract_text() or ""
        doi = _extract_doi(first_page_text)

    year: Optional[int] = None
    date_str = meta.get("/CreationDate") or meta.get("/ModDate")
    if date_str:
        m = re.search(r"(\d{4})", str(date_str))
        if m:
            candidate = int(m.group(1))
            if 1900 <= candidate <= datetime.date.today().year + 1:
                year = candidate

    return {
        "title": title,
        "authors": authors,
        "doi": doi,
        "year": year,
        "abstract": None,
    }


def resolve_pdf_metadata(pdf_path: str) -> PaperMetadata:
    """Run the full metadata pipeline for a PDF file.

    Resolution order:
      1. DOI found in first-page text  -> resolve_doi()
      2. Title found in embedded fields -> CrossRef title search
      3. Partial record from whatever was extracted (caller prompts for missing fields)

    Raises FileNotFoundError if the path does not exist, or pypdf errors on corrupt PDFs.
    """
    raw = extract_pdf_metadata(pdf_path)

    if raw["doi"]:
        try:
            return resolve_doi(raw["doi"])
        except ValueError:
            pass

    if raw["title"]:
        meta = _try_crossref_title(raw["title"])
        if meta:
            return meta

    authors: list[str] = []
    if raw["authors"]:
        # Split on semicolons first, then commas — handles "Doe, John; Smith, Jane"
        parts = re.split(r";", raw["authors"])
        authors = [p.strip() for p in parts if p.strip()]

    pub_date = datetime.date.today()
    if raw["year"]:
        pub_date = datetime.date(raw["year"], 1, 1)

    return PaperMetadata(
        paper_id=_pdf_paper_id(pdf_path),
        version=1,
        title=raw["title"] or "",
        authors=authors,
        published=pub_date,
        summary="",
        source="pdf",
    )
