// Generated by `npm run types:gen` from the #[derive(TS)] wire types across
// the workspace. DO NOT EDIT — `npm run types:check` fails when this file drifts
// from the Rust source. Frontend-facing aliases and the shapes that have no
// single Rust struct live in ./api.ts.

export type PaperDetails = {
  paper_id: number,
  source_id: string,
  version: number,
  title: string,
  summary: string | null,
  published: string | null,
  updated: string | null,
  url: string | null,
  doi: string | null,
  category: string | null,
  categories: Array<string>,
  journal_ref: string | null,
  comment: string | null,
  authors: Array<string>,
  tags: Array<string>,
  has_pdf: boolean,
  pdf_path: string | null,
  source: string | null,
  downloaded_source: boolean,
  /**
   * Never null: PAPER.SOURCE_FK is NOT NULL and every reader selects from
   * the `papers` view.
   */
  source_fk: number,
};

export type SearchResultOut = {
  source_id: string,
  version: number,
  title: string,
  summary: string,
  authors: Array<string>,
  /**
   * "" when published is the `0001-01-01` sentinel; else ISO date.
   */
  published: string,
  paper_url: string,
  primary_category: string,
  /**
   * The `source_id` verbatim; `source_id` above is namespace-stripped.
   */
  entry_id: string,
};

export type ArxivSearchResponse = {
  results: Array<SearchResultOut>,
  /**
   * Which results the library already holds (stripped ids).
   */
  saved_source_ids: Array<string>,
};

export type ArxivFetchResponse = {
  paper: SearchResultOut,
  saved: boolean,
  /**
   * Stripped id — the stored id when saved, else the fetched one.
   */
  source_id: string,
};

export type OpenAlexSearchResponse = {
  results: Array<SearchResultOut>,
  /**
   * Which results the library already holds (stripped ids).
   */
  saved_source_ids: Array<string>,
};

export type Status = "active" | "archived" | "deleted";

export type ProjectOut = {
  /**
   * Never null: `ProjectDetails.id` is optional only because that struct
   * doubles as the pre-insert shape; `to_out` refuses a row without an id.
   */
  id: number,
  name: string,
  description: string,
  color_hex: string | null,
  project_tags: Array<string>,
  source_ids: Array<string>,
  paper_count: number,
  status: Status,
  created_at: string | null,
  updated_at: string | null,
  archived_at: string | null,
  share_id: string | null,
};

export type NoteDetails = {
  /**
   * NOTE_SK is the primary key; a read row always has one.
   */
  id: number,
  /**
   * Stable identity (uuid v4) surviving export/import + share.
   */
  uuid: string,
  source_fk: number,
  paper_id_fk: number | null,
  project_id: number | null,
  title: string,
  content: string,
  created_at: string | null,
  updated_at: string | null,
};

export type AnnotationDetails = {
  id: number,
  /**
   * Stable identity (uuid v4) surviving export/import + share.
   */
  uuid: string,
  source_fk: number,
  project_id: number | null,
  anchor: string,
  comment: string,
  created_at: string | null,
  updated_at: string | null,
};

export type BasicAuthorDetails = {
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type AuthorWithCount = {
  paper_count: number,
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type AuthorPaperPreview = {
  paper_id: number,
  source_id: string,
  source_fk: number,
  version: number,
  title: string | null,
};

export type AuthorWithPapers = {
  paper_count: number,
  papers: Array<AuthorPaperPreview>,
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type Stats = {
  paper_count: number,
  tag_count: number,
  category_count: number,
  pdf_count: number,
  recent_papers: Array<PaperDetails>,
};

export type DoiVersionCandidate = {
  source_fk: number,
  source_id: string,
  title: string,
  source: string | null,
  published: string | null,
  doi: string,
};

export type FullTextReceipt = {
  source_id: string,
  version: number,
  indexed: boolean,
  chars?: number,
  reason?: string,
};

export type PaperMembershipReceipt = {
  ok: boolean,
  project_id: number,
  paper_id: string,
  paper_count: number,
};

export type BibtexImportReceipt = {
  saved_count: number,
  source_ids: Array<string>,
};

export type MergeReceipt = {
  winner_source_fk: number,
  winner_source_id: string,
  /**
   * The id that no longer exists after the merge.
   */
  merged_source_id: string,
  notes_moved: number,
  annotations_moved: number,
  memberships_moved: number,
  /**
   * Loser memberships dropped because the winner was already in the project.
   */
  memberships_collapsed: number,
  reading_statuses_moved: number,
  /**
   * Loser versions the winner lacked, re-keyed under the winner (same
   * version numbers).
   */
  versions_transplanted: number,
  /**
   * Loser versions collapsed into the winner's same-numbered versions.
   */
  versions_collapsed: number,
  /**
   * Tags the loser carried that the winner didn't (now unioned in).
   */
  tags_added: Array<string>,
  /**
   * Loser PDFs renamed to winner on-disk names in the managed dir.
   */
  pdfs_renamed: number,
  /**
   * Loser PDFs that filled a PDF-less winner version — renamed in, or
   * pointed at in place when they cannot be moved.
   */
  pdfs_adopted: number,
  /**
   * Duplicate loser PDFs unlinked after commit.
   */
  pdfs_deleted: number,
  /**
   * Duplicate loser PDFs left on disk because they live outside the
   * managed PDF dir.
   */
  pdfs_kept_external: number,
  /**
   * Loser versions whose stored PDF path had no file behind it
   * (transplants/adoptions found gone pre-rename, duplicates found gone
   * post-commit).
   */
  pdfs_missing: number,
};

export type FilterField = "TITLE" | "SUMMARY" | "AUTHOR";

export type FilterAction = "DENY" | "ALLOW";

export type FilterRule = {
  rule_id: number,
  field: FilterField,
  keywords: string,
  action: FilterAction,
  enabled: boolean,
};

export type GraphPaper = {
  /**
   * Node id — `PAPER_ROOTS.SOURCE_FK` as a string, so every id in the payload is
   * one comparable type; [`Self::source_fk`] is the `/library/:sfk` route param.
   */
  id: string,
  source_fk: number,
  /**
   * `PAPER_ROOTS.SOURCE_ID` — the vocabulary the project picker speaks.
   */
  source_id: string,
  /**
   * `PAPER.TITLE` (NOT NULL); an empty string stays empty so the title
   * filter can compare it unguarded.
   */
  label: string,
  category: string | null,
  /**
   * Display spellings of this paper's tags, deduped on [`norm_tag`] and resolved
   * to the TAG table's casing — the canvas chips, in [`Self::tag_keys`] order.
   */
  tags: Array<string>,
  /**
   * [`norm_tag`] of each entry in [`Self::tags`] — what a tag filter row is
   * compared against, so the client needs no normalization pass.
   */
  tag_keys: Array<string>,
  has_pdf: boolean,
  /**
   * `PAPER_META.PUBLISHED`, with the [`NO_PUBLISHED_DATE`] sentinel folded to
   * `None` so a Date-range filter cannot drop undated papers as year-1 "too old".
   */
  published: string | null,
  url: string | null,
  doi: string | null,
  summary: string | null,
  /**
   * Ids of the ACTIVE projects holding this paper, ascending.
   */
  project_ids: Array<number>,
  /**
   * Lowercased names of this paper's authors — what the Author highlight
   * filter substring-matches.
   */
  author_keys: Array<string>,
};

export type GraphAuthor = {
  /**
   * `author::<AUTHOR_FK>`.
   */
  id: string,
  /**
   * AUTHOR_FK, the `/authors/:id` route param.
   */
  author_id: number,
  /**
   * `AUTHOR.AUTHOR_FULL_NAME` — the canonical spelling, so it follows renames
   * and merges that `PAPER_META.AUTHORS` does not see.
   */
  label: string,
  /**
   * Papers on THIS canvas joined to this author — the hover inspector's degree line.
   */
  paper_count: number,
};

export type GraphTag = {
  /**
   * `tag::<key>`.
   */
  id: string,
  /**
   * [`norm_tag`] of the label — the key a tag filter row matches on.
   */
  key: string,
  /**
   * `TAG.TAG`, the spelling the Tags page shows; a tag `list_all_tags` omits
   * (the reading-list marker) keeps the paper's own casing.
   */
  label: string,
  paper_count: number,
};

export type GraphEdge = {
  source: string,
  target: string,
};

export type GraphProject = {
  id: number,
  name: string,
  /**
   * Always set: falls back to the app's default accent for a project with
   * no colour of its own.
   */
  color: string,
  /**
   * `PROJECT_TO_TAG` labels, ordered by label, with the reserved reading-list
   * marker removed — bookkeeping nobody typed, filtered out on every surface.
   */
  tags: Array<string>,
  /**
   * Whether any paper on THIS canvas belongs to the project — an active project
   * with no drawn paper can only empty the canvas, so the frontend narrows what it OFFERS.
   */
  on_graph: boolean,
};

export type GraphView = {
  papers: Array<GraphPaper>,
  authors: Array<GraphAuthor>,
  tags: Array<GraphTag>,
  edges: Array<GraphEdge>,
  /**
   * Distinct `latest_papers.category`, for the Category box.
   */
  categories: Array<string>,
  projects: Array<GraphProject>,
};

export type TagWithCount = {
  label: string,
  paper_count: number,
};

export type NewVersion = {
  source_fk: number,
  source_id: string,
  title: string,
  version: number,
};

export type OrcidCandidate = {
  author_id: number,
  full_name: string,
  doi: string,
};

export type ImportPreview = {
  project_name: string,
  description: string,
  paper_count: number,
  note_count: number,
  annotation_count: number,
  has_pdfs: boolean,
  format_version: number,
};

export type BackupInfo = {
  path: string,
  bytes: number,
};

export type PreMigrationBackup = {
  name: string,
  path: string,
  bytes: number,
  modified_at: string,
};

export type ImportReport = {
  roots: number,
  papers: number,
  paper_meta: number,
  authors: number,
  tags: number,
  projects: number,
  paper_links: number,
  project_links: number,
  notes: number,
  annotations: number,
  pdf_refs_cleared: number,
};

export type DeletedPaperDetails = {
  source_fk: number,
  source_id: string,
  title: string,
  authors: Array<string>,
  published: string | null,
  deleted_at: string | null,
  pdf_path: string | null,
  had_pdf: boolean,
  project_fks: Array<number>,
};

export type TrashedProjectRow = {
  deleted_at: string | null,
  /**
   * Never null: `ProjectDetails.id` is optional only because that struct
   * doubles as the pre-insert shape; `to_out` refuses a row without an id.
   */
  id: number,
  name: string,
  description: string,
  color_hex: string | null,
  project_tags: Array<string>,
  source_ids: Array<string>,
  paper_count: number,
  status: Status,
  created_at: string | null,
  updated_at: string | null,
  archived_at: string | null,
  share_id: string | null,
};

export type RestoredPaper = {
  ok: boolean,
  restored: string,
  pdf_path: string | null,
  project_fks: Array<number>,
};

export type EditorProjectSummary = {
  noteId: number,
  projectName: string,
  mainFile: string,
  sourceFk: number,
  projectId: number | null,
  updatedAt: string | null,
};

export type SavedPdf = {
  source_id: string,
  source_fk: number,
  title: string,
  /**
   * The paper's latest version, from `list_pdf_papers`.
   */
  version: number,
  size_bytes: number,
};

export type MergeCandidates = {
  /**
   * Shares this author's ORCID — near-certain duplicate.
   */
  candidates: Array<BasicAuthorDetails>,
  /**
   * Shares only the exact full name — weak evidence, never overlaps `candidates`.
   */
  name_candidates: Array<BasicAuthorDetails>,
};

export type PapersListing = {
  papers: Array<PaperDetails>,
};

export type PaperVersionMeta = {
  version: number,
  published: string | null,
  updated: string | null,
  has_pdf: boolean,
};

export type PaperVersionsResponse = {
  source_id: string,
  latest_version: number,
  versions: Array<PaperVersionMeta>,
};

export type DoiCandidates = {
  candidates: Array<DoiVersionCandidate>,
};

export type FullTextPending = {
  pending: number,
};

export type FullTextDiffResponse = {
  from_version: number,
  to_version: number,
  hunks: Array<DiffHunk>,
};

export type DiffHunk = {
  pos: number,
  delete_len: number,
  insert: string,
};

export type SavedSourceIds = {
  saved_source_ids: Array<string>,
};

export type DeletedPaperReceipt = {
  deleted: string,
};

export type RemovedFromProjects = {
  ok: boolean,
  removed_from_projects: Array<number>,
};

export type OkReceipt = {
  ok: boolean,
};

export type PaperImportResult = {
  source_id: string,
  title: string,
};

export type ImportPreviewResponse = {
  project_name: string,
  description: string,
  paper_count: number,
  note_count: number,
  has_pdfs: boolean,
  format_version: number,
};

export type ImportedProject = {
  project_id: number,
};

export type SavedPdfListing = {
  pdfs: Array<SavedPdf>,
};

export type DeletedPdf = {
  deleted: boolean,
};

export type ProjectsResponse = {
  projects: Array<ProjectOut>,
};

export type CreatedProject = {
  project: { id: number, name: string, },
};

export type BulkAddReceipt = {
  ok: boolean,
  failed: Array<string>,
};

export type TagsResponse = {
  tags: Array<TagWithCount>,
};

export type TagDetail = {
  label: string,
  papers: Array<PaperDetails>,
  projects: Array<ProjectOut>,
};

export type AuthorsResponse = {
  authors: Array<AuthorWithCount>,
};

export type AuthorMergeResponse = {
  merged_ids: Array<number>,
  paper_count: number,
  papers: Array<AuthorPaperPreview>,
  author_id: number,
  orcid: string | null,
  full_name: string | null,
  first_name: string | null,
  last_name: string | null,
};

export type PaperMetadata = {
  /**
   * Namespaced ID, e.g. "arxiv:2204.12985", "openalex:W31...", "local:{hash}".
   */
  source_id: string,
  /**
   * Defaults to 1 for non-arxiv sources.
   */
  version: number,
  title: string,
  authors: Array<string>,
  published: string,
  updated: string | null,
  summary: string,
  category: string | null,
  categories: Array<string> | null,
  doi: string | null,
  journal_ref: string | null,
  comment: string | null,
  url: string | null,
  tags: Array<string> | null,
  /**
   * Backend that produced this record; stored as PAPER_META.PROVIDER.
   */
  source: string | null,
  /**
   * Index-aligned with `authors` (same length when present); `None` per-author
   * where the source didn't carry one. crossref/openalex + import set it.
   */
  author_orcids: Array<string | null> | null,
};

export type OpenAlexSaveResponse = {
  saved: boolean,
  source_id: string,
};

export type DoiResolveResponse = {
  metadata: PaperMetadata,
};

export type DoiSaveResponse = {
  metadata: PaperMetadata,
  saved: boolean,
};

export type NoteListResponse = {
  notes: Array<NoteDetails>,
};

export type NoteGetResponse = {
  note: NoteDetails,
};

export type DeletedNote = {
  deleted_note_id: number,
};

export type AnnotationListResponse = {
  annotations: Array<AnnotationDetails>,
};

export type CreatedAnnotation = {
  id: number,
};

export type ReadingStatusesResponse = {
  statuses: Record<string, "reading" | "read">,
};

export type ReadingStatusReceipt = {
  ok: boolean,
  applied: number,
};

export type EditorProjectsResponse = {
  projects: Array<EditorProjectSummary>,
};

export type SearchHistoryResponse = {
  suggestions: Array<string>,
};

export type VersionCheckResponse = {
  checked: number,
  new_versions: Array<NewVersion>,
};

export type NewVersionsResponse = {
  new_versions: Array<NewVersion>,
};

export type FeedRulesResponse = {
  rules: Array<FilterRule>,
};

export type CreatedFeedRule = {
  rule_id: number,
};

export type OrcidBackfillResponse = {
  checked: number,
  updated: Array<OrcidCandidate>,
  /**
   * DOIs where a source request failed (not just "no ORCID found").
   */
  errored: number,
};

export type HardDeletedPaper = {
  ok: boolean,
  hard_deleted: string,
};

export type RestoredProject = {
  ok: boolean,
  restored_project_id: number,
};

export type HardDeletedProject = {
  ok: boolean,
  hard_deleted_project_id: number,
};

export type PaperSavedBody = {
  source_ids: Array<string>,
};

export type PaperMergeBody = {
  loser_source_fk: number,
};

export type RepairFields = {
  title: string,
  authors: Array<string>,
  /**
   * Publication date (YYYY-MM-DD).
   */
  published: string,
  summary?: string,
  category?: string | null,
  doi?: string | null,
  url?: string | null,
  tags?: Array<string> | null,
};

export type VersionsCheckBody = {
  limit?: number,
};

export type VersionsAckBody = {
  source_fk: number,
};

export type UploadPdfBody = {
  file_b64: string,
};

export type ImportPdfBody = {
  file_b64: string,
  filename?: string | null,
};

export type RecognizeBody = {
  input: string,
};

export type ImportPdfUrlBody = {
  url: string,
  project_id?: number | null,
};

export type RecognizedInput = {
  "kind": "arxiv_id",
  "value": string } | { "kind": "doi",
  "value": string } | { "kind": "direct_pdf_url",
  "value": string } | { "kind": "unrecognized"
};

export type ImportBibtexBody = {
  file_b64: string,
  project_id?: number | null,
};

export type ImportPreviewBody = {
  file_b64: string,
};

export type ImportCommitBody = {
  file_b64: string,
  on_conflict?: string | null,
};

export type OrcidBackfillBody = {
  limit?: number,
};

export type TagCreateBody = {
  label: string,
};

export type PaperTagsBody = {
  tags: Array<string>,
};

export type StorageBackupBody = {
  dest_path: string,
};

export type StorageRestoreBody = {
  src_path: string,
};

export type StorageImportBody = {
  src_path: string,
};

export type ArxivSearchBody = {
  query: string,
  max_results?: number,
  save?: boolean,
  sort?: string,
};

export type ArxivFetchBody = {
  source_id: string,
  save?: boolean,
};

export type OpenAlexSearchBody = {
  query: string,
  max_results?: number,
  sort?: string,
};

export type OpenAlexSaveBody = {
  source_id: string,
};

export type CrossrefSearchBody = {
  query: string,
  max_results?: number,
};

export type DoiResolveBody = {
  doi: string,
};

export type DoiSaveBody = {
  doi: string,
};

export type FeedDismissBody = {
  arxiv_id: string,
  version: number,
  permanent?: boolean,
};

export type FeedRuleCreateBody = {
  field: FilterField,
  keywords: string,
  action?: FilterAction,
};

export type CreateEditorProjectBody = {
  project_name: string,
  main_file?: string,
  source_id?: string | null,
  project_id?: number | null,
};

export type EnvPatchBody = {
  key: string,
  value: string,
};

export type NoteCreateBody = {
  source_id: string,
  project_id?: number | null,
  paper_id?: number | null,
  title?: string,
  content?: string,
};

export type NoteUpdateBody = {
  title?: string | null,
  content?: string | null,
};

export type AuthorUpdateBody = {
  full_name?: string | null,
  first_name?: string | null,
  last_name?: string | null,
  orcid?: string | null,
};

export type AuthorMergeBody = {
  duplicate_ids?: Array<number>,
};

export type AnnotationCreateBody = {
  source_id: string,
  project_id?: number | null,
  anchor: string,
  comment?: string,
};

export type AnnotationUpdateBody = {
  comment: string,
  /**
   * Omitted/null keeps the stored anchor; set to recolor a highlight.
   */
  anchor?: string | null,
};

export type ReadingStatusPutBody = {
  status: string,
};

export type ProjectCreateBody = {
  name: string,
  description?: string,
  color_hex?: string | null,
  project_tags?: Array<string>,
};

export type ProjectUpdateBody = {
  name?: string | null,
  description?: string | null,
  color_hex?: string | null,
  status?: string | null,
  project_tags?: Array<string> | null,
};

export type ProjectAddPaperBody = {
  source_id: string,
};

export type ProjectAddPapersBulkBody = {
  source_ids: Array<string>,
};

export type ProjectExportBody = {
  dest_path?: string | null,
  include_pdfs?: boolean,
};

export type FsOp = {
  "kind": "list",
  path: string,
  } | { "kind": "readFile",
  path: string,
  } | { "kind": "writeFile",
  path: string,
  data: string,
  binary?: boolean,
  } | { "kind": "mkdir",
  path: string,
  } | { "kind": "remove",
  path: string,
  recursive?: boolean,
};

export type DirEntry = {
  name: string,
  /**
   * The guest re-joins each basename to the parent.
   */
  kind: "file" | "directory",
};

export type FsResult = {
  "kind": "list",
  entries: Array<DirEntry>,
  } | { "kind": "readFile",
  data: string,
  binary: boolean,
  } | { "kind": "ok"
};

export type SummaryRow = {
  share_id: string,
  name: string,
  description?: string,
  paper_count: number,
  note_count: number,
  tag_count: number,
  synced_at: string | null,
  paused: boolean,
  project_fk?: number | null,
  e2ee?: boolean,
  member_count?: number,
  pending?: boolean,
  role?: "admin" | "co-admin" | "editor" | "viewer",
};

export type SharedProjectsListing = {
  shared_projects: Array<SummaryRow>,
};

export type ReceivedListing = {
  received: Array<SummaryRow>,
};

export type ImportedReceipt = {
  project_fk: number,
};

export type UnpublishedReceipt = {
  unpublished: boolean,
  share_id: string,
  e2ee?: boolean,
};

export type LeftReceipt = {
  left: boolean,
  forgotten: boolean,
};

export type UnlinkedReceipt = {
  unlinked: boolean,
};

export type PublishedReceipt = {
  share_id: string,
  e2ee?: boolean,
};

export type TicketMinted = {
  ticket: string,
  share_id: string,
};

export type MemberCode = {
  code: string,
};

export type InviteMinted = {
  invite: string,
};

export type MemberRow = {
  member_id: string,
  name: string | null,
  role: "admin" | "co-admin" | "editor" | "viewer",
  invited_at: string,
  revoked: boolean,
  verified: boolean,
  /**
   * Re-sendable while the grant stands; `None` once revoked. Only the
   * device that minted the invite has it (bearer secret, never synced).
   */
  invite: string | null,
};

export type MembersListing = {
  members: Array<MemberRow>,
  /**
   * This device's member id — how the UI finds "this device" in `members`.
   * Absent on the store-only legacy path (no live node).
   */
  self_member_id?: string,
  /**
   * This device's admin-tier standing; member routes require admin-tier.
   */
  self_role?: "admin" | "co-admin",
};

export type PresenceListing = {
  members: Array<PresenceRow>,
  self_member_id: string,
};

export type PresenceRow = {
  member_id: string,
  name: string | null,
  /**
   * RFC 3339 of the member's last sync pass.
   */
  last_seen: string,
  /**
   * Heartbeat within two sync intervals.
   */
  online: boolean,
  /**
   * Shared paper being read (opt-in); `None` unless online.
   */
  reading: string | null,
};

export type PresenceUpdate = {
  /**
   * `source_id` of the paper being read; `None` clears the indicator.
   */
  reading?: string | null,
};

export type RoleChanged = {
  member_id: string,
  role: string,
};

export type AdminTransferred = {
  transferred: boolean,
  /**
   * The new THE ADMIN's member id (hex).
   */
  admin: string,
};

export type RevokedReceipt = {
  revoked: boolean,
};

export type RekeyedReceipt = {
  rekeyed: boolean,
  members: number,
};

export type RemovedReceipt = {
  removed: boolean,
  member_id: string,
};

export type SharedPdfSaved = {
  source_id: string,
  version: number,
  path: string,
};

export type SyncDirection = "two_way" | "shared_to_local" | "local_to_shared";

export type ShareSettings = {
  paused: boolean,
  direction: SyncDirection,
};

export type DeviceActor = {
  actor: string | null,
};

export type ChangeRow = {
  hash: string,
  actor: string,
  /**
   * Unix seconds; 0 on changes written before timestamps landed.
   */
  time: number,
  message: string | null,
  /**
   * Written by this device (its pinned actor id).
   */
  mine: boolean,
  /**
   * Host-assigned name from the node's Member List; None when unnamed.
   */
  display_name: string | null,
};

export type Timeline = {
  changes: Array<ChangeRow>,
  device_actor: string | null,
};

export type PaperChange = {
  source_id: string,
  title: string,
  /**
   * Local `/library/{sfk}` target; None when unresolvable or trashed.
   */
  source_fk: number | null,
};

export type EntryChange = {
  uuid: string,
  title: string,
  from: string | null,
  to: string | null,
  /**
   * Notes only: local `/notes/{id}` target; None when unresolvable.
   */
  note_id: number | null,
  /**
   * Annotations only: their paper's `/library/{sfk}`; None when unresolvable.
   */
  paper_sfk: number | null,
};

export type FieldChange = {
  field: string,
  from: string,
  to: string,
};

export type HistoryDiff = {
  papers_added: Array<PaperChange>,
  papers_removed: Array<PaperChange>,
  tags_added: Array<string>,
  tags_removed: Array<string>,
  notes_added: Array<EntryChange>,
  notes_removed: Array<EntryChange>,
  notes_changed: Array<EntryChange>,
  annotations_added: Array<EntryChange>,
  annotations_removed: Array<EntryChange>,
  annotations_changed: Array<EntryChange>,
  meta: Array<FieldChange>,
};

export type RestoredToChange = {
  ok: boolean,
  removed_papers: number,
  removed_notes: number,
  removed_annotations: number,
  removed_tags: number,
};

export type RestoreBody = {
  /**
   * Change hash to restore to (state as of that change, inclusive).
   */
  to: string,
};

export type SyncRole = "hoster" | "reader";

export type SyncReason = "paused" | "direction" | "project gone" | "no ticket" | "bad ticket" | "p2p offline" | "awaiting first sync" | "no key for any content" | "revoked or awaiting key";

export type SyncSkipped = {
  synced: false,
  reason: SyncReason,
  role?: SyncRole,
};

export type SyncedReceipt = {
  synced: true,
  role: SyncRole,
  e2ee?: boolean,
  /**
   * Hoster leg: devices this share is currently granted to.
   */
  members?: number,
  /**
   * Reader leg: commits decrypted and applied this pass.
   */
  applied?: number,
  /**
   * Reader leg: commits fetched with no key for their epoch.
   */
  no_key?: number,
  /**
   * Reader leg: commits that failed to decrypt for any other reason.
   */
  failed?: number,
  /**
   * The sync ran but the mirror is still empty — the host has not answered.
   */
  pending?: boolean,
  reason?: SyncReason,
  /**
   * Notes/annotations skipped: key revoked or not yet received.
   */
  undecryptable?: number,
};

export type ApiRequest = {
  method: string,
  path: string,
  body?: unknown,
};

export type ApiError = {
  status: number,
  detail: string,
};

export type RemoteError = {
  "kind": "unreachable",
  detail: string,
  } | { "kind": "remote",
  status: number,
  detail: string,
  } | { "kind": "transport",
  detail: string,
  } | { "kind": "invalid",
  detail: string,
};
