//! pdfium binding, native library discovery, and in-process extraction.

use std::sync::OnceLock;

use pdfium_render::prelude::*;

use super::scan::{
    extract_arxiv_id, extract_doi, extract_title_from_text, looks_autogenerated, looks_junk_author,
    parse_year,
};

// ---------------------------------------------------------------------------
// Raw extraction result.
// ---------------------------------------------------------------------------

#[derive(Debug, Default, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(default)]
pub(crate) struct Extracted {
    pub title: Option<String>,
    pub authors: Option<String>,
    pub doi: Option<String>,
    pub arxiv_id: Option<String>,
    pub year: Option<i32>,
    /// pdfium rejected the bytes as malformed (FPDF_ERR_FORMAT). Distinct from
    /// all-None: a PDF that opens but carries no metadata leaves this false.
    pub unreadable: bool,
}

// ---------------------------------------------------------------------------
// pdfium binding + Info dict + first-page text
// ---------------------------------------------------------------------------

/// Resolve the libpdfium path ONCE. Order: `LINXIV_PDFIUM_LIB` env → `pdfium/`
/// next to the executable → the dev vendor dir, `cfg(debug_assertions)`-gated so
/// it can't ship in a release binary; `None` → the system library at bind time.
pub(crate) fn pdfium_lib_path() -> Option<&'static std::path::Path> {
    static LIB: OnceLock<Option<std::path::PathBuf>> = OnceLock::new();
    LIB.get_or_init(|| {
        let in_dir = |dir: std::path::PathBuf| {
            let p = Pdfium::pdfium_platform_library_name_at_path(&dir);
            p.exists().then_some(p)
        };
        if let Some(p) = std::env::var_os("LINXIV_PDFIUM_LIB") {
            return Some(std::path::PathBuf::from(p));
        }
        if let Some(p) = std::env::current_exe()
            .ok()
            .and_then(|e| e.parent().map(|d| d.join("pdfium")))
            .and_then(in_dir)
        {
            return Some(p);
        }
        #[cfg(debug_assertions)]
        if let Some(p) = in_dir(std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../vendor/pdfium/lib"
        ))) {
            return Some(p);
        }
        None
    })
    .as_deref()
}

/// Bind libpdfium for a SINGLE extraction; per-call bind+drop releases the
/// process-global lock each time (see concurrent_extractions_do_not_deadlock).
fn bind_pdfium() -> Option<Pdfium> {
    let bindings = match pdfium_lib_path() {
        Some(p) => Pdfium::bind_to_library(p).ok(),
        None => Pdfium::bind_to_system_library().ok(),
    };
    match bindings {
        Some(b) => Some(Pdfium::new(b)),
        None => {
            static WARNED: std::sync::Once = std::sync::Once::new();
            WARNED.call_once(|| {
                tracing::error!(
                    "libpdfium not found — PDF metadata extraction disabled; run \
                     scripts/fetch_pdfium.sh or set LINXIV_PDFIUM_LIB"
                )
            });
            None
        }
    }
}

/// Non-empty Info-dict value for `tag`, else None; capped at 300 chars.
fn meta_get(md: &PdfMetadata, tag: PdfDocumentMetadataTagType) -> Option<String> {
    let v = md.get(tag)?.value().to_string();
    let capped: String = v.chars().take(300).collect();
    (!capped.trim().is_empty()).then_some(capped)
}

// ---------------------------------------------------------------------------
// extract_pdf_metadata — catch-and-fall-through over the whole pipeline
// ---------------------------------------------------------------------------

/// SYNCHRONOUS, BLOCKING native FFI. Async callers reach it through
/// `resolve_pdf_metadata`, which runs the isolated wrapper on `spawn_blocking`.
pub(crate) fn extract_pdf_metadata(bytes: &[u8]) -> Extracted {
    // Bind a fresh Pdfium, extract, and drop it within this call (see `bind_pdfium`
    // for the lock mechanism that makes a short-lived instance the correct choice).
    // catch_unwind degrades a pdfium *panic* to all-None; D30 pins the release
    // profile to `panic = "unwind"` for it (src-tauri/Cargo.toml). A native
    // libpdfium *segfault* is uncatchable — `extract_pdf_metadata_isolated` is
    // the subprocess boundary covering that.
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let Some(pdfium) = bind_pdfium() else {
            return Extracted::default();
        };
        let doc = match pdfium.load_pdf_from_byte_slice(bytes, None) {
            Ok(doc) => doc,
            Err(PdfiumError::PdfiumLibraryInternalError(PdfiumInternalError::FormatError)) => {
                return Extracted {
                    unreadable: true,
                    ..Extracted::default()
                };
            }
            // Password/security/other load errors: keep degrading to all-None.
            Err(_) => return Extracted::default(),
        };
        extract_from_doc(&doc)
    }))
    .unwrap_or_default()
}

fn extract_from_doc(doc: &PdfDocument) -> Extracted {
    let md = doc.metadata();
    let mut title = meta_get(md, PdfDocumentMetadataTagType::Title);
    let mut authors = meta_get(md, PdfDocumentMetadataTagType::Author);
    let date_str = meta_get(md, PdfDocumentMetadataTagType::CreationDate)
        .or_else(|| meta_get(md, PdfDocumentMetadataTagType::ModificationDate));

    if title.as_deref().is_some_and(looks_autogenerated) {
        title = None;
    }
    if authors.as_deref().is_some_and(looks_junk_author) {
        authors = None;
    }

    // First-page text only. pdfium emits proper newlines, so extract_title_from_text
    // sees one logical line per visual line (joins <=3 of them, caps at 300 chars).
    let first_page = doc
        .pages()
        .first()
        .ok()
        .and_then(|p| p.text().ok().map(|t| t.all()))
        .unwrap_or_default();

    let doi = extract_doi(&first_page);
    let arxiv_id = extract_arxiv_id(&first_page);

    if title.is_none() && !first_page.is_empty() {
        title = extract_title_from_text(&first_page);
    }

    let year = date_str.as_deref().and_then(parse_year);

    Extracted {
        title,
        authors,
        doi,
        arxiv_id,
        year,
        unreadable: false,
    }
}

// ---------------------------------------------------------------------------
// Tests — D10 spikes over the committed real PDFs, skipped (not failed)
// without libpdfium or a fixture; see `load_spike_pdf`. No network: the
// junk-byte resolves find no id/DOI/title to enrich from.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sources::pdf_metadata::resolve_pdf_metadata;

    // ---- D10 SPIKE: real committed PDFs (pdfium extraction, no network) ----

    // Skip guard for the spike tests: print why and return `None` for the caller
    // to early-return on, rather than fail the suite on a dev/sparse checkout.
    fn load_spike_pdf(name: &str) -> Option<Vec<u8>> {
        if bind_pdfium().is_none() {
            eprintln!(
                "skipping {name}: libpdfium not available (run scripts/fetch_pdfium.sh or set LINXIV_PDFIUM_LIB)"
            );
            return None;
        }
        let p = format!(
            "{}/../../../tests/test_file/{name}",
            env!("CARGO_MANIFEST_DIR")
        );
        match std::fs::read(&p) {
            Ok(b) => Some(b),
            Err(e) => {
                eprintln!("skipping {name}: fixture not found ({p}): {e}");
                None
            }
        }
    }

    // pdf-extract took ~183s on this 76-page/29MB paper's first page;
    // pdfium ~0.3s (lopdf ~5s), fast enough to run inline. Only the arXiv id is
    // asserted: it is what drives enrichment to the real title/authors.
    #[test]
    fn spike_multi_author_2411_fast() {
        let Some(bytes) = load_spike_pdf("2411.10406v2.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        assert_eq!(m.arxiv_id.as_deref(), Some("2411.10406v2"));
    }

    #[test]
    fn spike_embedded_meta_2604_21547() {
        let Some(bytes) = load_spike_pdf("2604.21547v1.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        assert_eq!(m.arxiv_id.as_deref(), Some("2604.21547v1"));
        assert!(
            m.title.as_deref().unwrap_or("").contains("Yang-Baxter"),
            "got title: {:?}",
            m.title
        );
        assert_eq!(m.authors.as_deref(), Some("Vinayak M. Kulkarni"));
        assert_eq!(m.doi, None);
    }

    #[test]
    fn spike_junk_author_2604_00068() {
        let Some(bytes) = load_spike_pdf("2604.00068v2.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        let title = m.title.expect("text-heuristic title");
        assert!(title.contains("Chandrasekhar"), "got title: {title:?}");
        assert_eq!(m.authors, None, "OS-junk author filtered out");
        assert_eq!(m.doi, None);
    }

    // Non-arXiv PDF: no arXiv id/DOI to enrich from, so a title regression here is
    // silent. Guards that the title doesn't swallow the page — pdfium's newlines
    // keep it one line per visual line.
    #[test]
    fn non_arxiv_text_title_is_bounded() {
        let Some(bytes) = load_spike_pdf("paper.pdf") else {
            return;
        };
        let m = extract_pdf_metadata(&bytes);
        let title = m.title.expect("text-heuristic title");
        assert!(
            title.chars().count() < 200,
            "title swallowed the page: {} chars",
            title.chars().count()
        );
        assert!(
            title.starts_with("Note on the construction"),
            "got: {title:?}"
        );
    }

    // Regression for the thread_local deadlock: pdfium-render's thread_safe holds a
    // process-global lock for a Pdfium's whole lifetime, so a per-thread instance
    // pinned it (the 2nd concurrent extraction blocked forever); per-call bind+drop
    // releases it. 8 resolves on a 4-worker runtime must all finish — the timeout
    // turns a regression into a failure, not a hung suite. Each call runs resolve's
    // full path, and the worker subprocess too when a worker binary resolves.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn concurrent_extractions_do_not_deadlock() {
        let data_dir = tempfile::tempdir().unwrap();
        let mut handles = Vec::new();
        for i in 0..8 {
            let data_dir_path = data_dir.path().to_path_buf();
            handles.push(tokio::spawn(async move {
                // Result is irrelevant — only completion (no deadlock) matters.
                let bytes = format!("%PDF junk {i}").into_bytes();
                let _ = resolve_pdf_metadata(&bytes, &data_dir_path, "", true).await;
            }));
        }
        let join_all = async {
            for h in handles {
                h.await.unwrap();
            }
        };
        tokio::time::timeout(std::time::Duration::from_secs(30), join_all)
            .await
            .expect("concurrent PDF extractions deadlocked (timed out)");
    }

    #[tokio::test]
    async fn malformed_pdf_is_a_pdf_import_error() {
        if bind_pdfium().is_none() {
            eprintln!("skipping malformed_pdf_is_a_pdf_import_error: libpdfium not available");
            return;
        }
        // %PDF magic + garbage: pdfium refuses to open it -> flagged, no panic.
        let m = extract_pdf_metadata(b"%PDF-1.4 not really a pdf");
        assert!(m.unreadable);
        assert_eq!(m.title, None);
        // resolve surfaces it as PdfImport (422) before any network call,
        // rather than saving a bare `local:` record.
        let dir = tempfile::tempdir().unwrap();
        let err = resolve_pdf_metadata(b"%PDF junk", dir.path(), "", true)
            .await
            .unwrap_err();
        assert!(
            matches!(err, crate::error::CoreError::PdfImport(_)),
            "{err:?}"
        );
        assert_eq!(err.http_status(), 422);
    }
}
